# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Essay', verbose_name='随笔'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='python_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PythonBlog', verbose_name='Python博客'),
        ),
    ]
