# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 11:02
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
    ]
